impactMarket/app

package.json
src/views/Beneficiary.tsx
src/views/Home.tsx

- Fixed bug when opening rules modal;
- Added alerts for "user blocked" and "funds remaining days";

Fixes in Beneficiary page

---

package.json
src/components/Select.tsx
src/utils/countries.tsx
src/utils/currencies.tsx
src/utils/languages.tsx
src/views/profile/Profile.tsx
src/views/profile/components/ImageForm.tsx
src/views/profile/components/PersonalForm.tsx
src/views/settings/Settings.tsx
src/views/settings/components/BasicForm.tsx
yarn.lock

- Created a wrapper for Select component;
- Added Select to the Settings page;
- Small bug fixing when updating the user info;
- Hide Country field in Profile page for now, need to discuss how it will work;

Add Select component from UI

---

src/hooks/useGuard.tsx

- Fixed a bug in the Guard component causing multiple re-renderings;

Fix Guard component

---

src/components/Select.tsx
src/utils/users.ts
src/views/profile/Profile.tsx
src/views/profile/components/ContactForm.tsx
src/views/profile/components/PersonalForm.tsx
src/views/settings/components/BasicForm.tsx

- Added Country field;
- Removed disabled status from Phone field (it's not saving for now, it needs to be added in the API);

Add Country and Phone fields in Profile page

---

customtypes/pwa-translations/index.json
src/api/community.ts
src/hooks/useGuard.tsx
src/pages/requests/[id].tsx
src/pages/requests/index.tsx
src/utils/routes.ts
src/views/Request.tsx
src/views/Requests.tsx

New repository clone and new branch for -> community requests page

[IPCT1-711] Community Requests V2

---

src/pages/profile.tsx
src/pages/settings.tsx
src/views/Profile/AditionalForm.tsx
src/views/Profile/ContactForm.tsx
src/views/Profile/DeleteForm.tsx
src/views/Profile/FormActions.tsx
src/views/Profile/ImageForm.tsx
src/views/Profile/PersonalForm.tsx
src/views/Profile/index.tsx
src/views/Settings/BasicForm.tsx
src/views/Settings/index.tsx

- Rename folder structure inside "views" folder according to new standards;

Refactor views folder structure

---

src/api/community.ts
src/modals/Stories/ReportStory.tsx
src/views/Stories/Filters.tsx
src/views/Stories/StoryList.tsx

- Only show countries with communities
- User unabled to report his own stories
- When a story is reported can no longer see it

Stories fix countries filter

---

src/components/Sidebar.tsx
src/hooks/useGuard.tsx
src/utils/users.ts
src/views/Beneficiary.tsx
src/views/Home.tsx
src/views/Profile/AditionalForm.tsx
src/views/Profile/ContactForm.tsx
src/views/Profile/PersonalForm.tsx
src/views/Stories/StoryList.tsx
src/views/Stories/index.tsx

- Fixed bug when clicking "cancel" button in Profile page with empty fields, it didn't returned to default state;
- Fixed logout bug when disconnecting wallet;
- Fixed form inputs default values;
- Refactor of the "checkUserPermission" function;

Fix multiple bugs

---

customtypes/pwa-translations/index.json
customtypes/pwa-view-profile/index.json
package.json
src/api/community.ts
src/views/Requests.tsx
yarn.lock

Fetch communities from that user's country.

get user country and show communities from that country as default

---

customtypes/pwa-translations/index.json
customtypes/pwa-view-profile/index.json
package.json
src/api/community.ts
src/views/Requests.tsx
yarn.lock

Revert "get user country and show communities from that country as default"

---

src/modals/Stories/CreateStory.tsx
src/views/Stories/Filters.tsx
src/views/Stories/StoryList.tsx
src/views/Stories/index.tsx

- Fixed image on mobile
- Fixed multiple requests on tab click

Stories Fixed

---

package.json
src/pages/_app.tsx
src/pages/_document.tsx
src/views/Proposals.tsx
src/views/Stories/StoryList.tsx
yarn.lock

- FIxed a bug on the loader when starting the APP;
- Installed the library "styled-components" to load the CSS on the server side;
- Fixed bug in Proposals page (map key elem was an object, passed a number instead);
- Fixed a bug in Stories page (bgImg should be a string, not arrow function);

Fixed bug when starting app

---

next.config.js
src/components/CanBeRendered.tsx
src/components/Select.tsx
src/constants/userTypes.ts
src/hooks/useFilters.tsx
src/views/Stories/Filters.tsx
src/views/Stories/StoryList.tsx
src/views/Stories/index.tsx

- Added a "CanBeRendered" component to render certain parts based on the user type;
- Fixed props in "Select" component;
- Added "initialValues" prop to "Select" component;
- Fixed "useFilters" hook to accommodate "Select" component in Stories page;

Multiple fixes

---

src/components/Input.tsx
src/components/Select.tsx
src/views/Beneficiary.tsx
src/views/Profile/PersonalForm.tsx
src/views/Profile/index.tsx

- Fixed error and success messages when claiming UBI;
- Added required prop to Input and Select components;
- Added required state to FirstName, LastName and Country in Profile page;
- Fixed error messages in Profile page;

Multiple bug fixing

---

package.json
src/modals/Stories/CreateStory.tsx
src/views/Stories/StoryList.tsx
yarn.lock

- Image component with trash icon
- Change stories limit to 10
- Resize country flags and align with country name

Image component with trash icon

---

src/hooks/useGuard.tsx

- Fixed a bug in userGuard component:
- When entering a page by refresh, the router component would have the correct URL;
- When navigating inside the App, the router component would always have the last URL and not the current which caused some security issues;

Bug fix in User Guard

---

package.json
src/modals/Stories/CreateStory.tsx
src/modals/Stories/DeleteStory.tsx
src/modals/Stories/ReportStory.tsx
src/views/Stories/StoryList.tsx
src/views/Stories/index.tsx
yarn.lock

- Title column 100% with when there is no "Create Story" button
- Text wrap
- Hide loves label when 0 loves
- Resize country flag
- Resize "Create Story" button 
- Creating stories with " " now disabled
- Create story modal buttons side by side
- DropDown with same height as loves button
- On refresh load on "My stories" if it was selected previously
-

Fixes from dogfooding

---

src/views/Stories/index.tsx
yarn.lock

- Remove "All stories" tab when logged out becouse it´s the only one available

Remove tab when logged out

---

src/utils/languages.tsx
src/views/Settings/BasicForm.tsx

- Show only the 4 available languages in Settings page;

Update available languages

---

src/views/Profile/ImageForm.tsx
src/views/Profile/index.tsx

- Fixed a bug with the loading state when uploading a image in Profile page;

Fix bug when uploading user image

---

package.json
src/views/Stories/StoryList.tsx
yarn.lock

Fix image resizing

---

src/hooks/useGuard.tsx
src/modals/AddBeneficiary.tsx
src/modals/index.ts
src/pages/manager/beneficiaries.tsx
src/utils/routes.ts
src/views/Beneficiaries.tsx

- Added Beneficiaries page for Managers (first phase, no listing of Beneficiaries);
- Added "Add Beneficiary" modal;

Add Beneficiares page and Add Beneficiary modal

---

src/components/Image.tsx

- Removed width and height props, becouse they where creating many warnings

Image component Fix

---

src/views/Stories/StoryList.tsx

- Change story card buttons design

Redesign story card

---

package.json
src/api/community.ts
src/views/Proposals/AddCommunityPage.tsx
src/views/Proposals/Community.tsx
src/views/Proposals/Proposal.tsx
src/views/Proposals/ProposalsPage.tsx
src/views/Proposals/index.tsx
yarn.lock

- Image with loader
- Local changes

Proposals Fixes

---

package.json
src/helpers/yup.ts
src/views/Profile/AditionalForm.tsx
src/views/Profile/ContactForm.tsx
src/views/Profile/PersonalForm.tsx
src/views/Profile/index.tsx
src/views/Settings/index.tsx
yarn.lock

- Installed Yup library to validate Profile fields:
- Email must be valid;
- Phone must be valid;
- Age must be between 1 and 150;
- Children must be equal or lower than 20;
- First Name and Last Name should have 30 or less characters each;

Multiple fixes in Profile

---

src/components/Sidebar.tsx
src/components/WrapperProvider.tsx
src/modals/WrongNetwork.tsx
src/modals/index.ts

- Added a example Modal to show a warning when the user is in the wrong network;
- Needs final design;

Add Wrong Network warning

---

src/components/Trim.tsx
src/views/Stories/Filters.tsx
src/views/Stories/StoryList.tsx

-Remove padding around image
-Change typography of story messages

Stories design changes

---

src/api/community.ts
src/components/ProgressBar.tsx
src/graph/community.ts
src/pages/manager/index.tsx
src/utils/routes.ts
src/views/Beneficiary.tsx
src/views/Home.tsx
src/views/Manager/Alerts.tsx
src/views/Manager/Cards.tsx
src/views/Manager/ProgressBar.tsx
src/views/Manager/index.tsx
yarn.lock

- Added Manager dashboard page
Notes:
- Secondary line of 4 cards is to be hidden for now, so i commented that part;
- Missing success/error handling on "Request more funds" action";

Add Manager dashboard page

---

src/graph/user.ts
src/pages/manager/beneficiaries/[id].tsx
src/utils/routes.ts
src/views/BeneficiaryDetail/StateButtons.tsx
src/views/BeneficiaryDetail/index.tsx

- Added Beneficiary detail page for Managers;
**NOTE:** Need to add a new request to the API to get User info. For now we're using TheGraph.

Add Beneficiary detail page

---

config.ts
package.json
src/api/story.ts
src/components/Image.tsx
src/modals/Stories/DeleteStory.tsx
src/modals/Stories/OpenStory.tsx
src/modals/Stories/ReportStory.tsx
src/modals/index.ts
src/views/Stories/StoryList.tsx
yarn.lock

Story open modal

---

src/components/Sidebar.tsx

- Show links in Sidebar for Managers;

Fix sidebar for Managers

---

src/api/user.ts
src/graph/user.ts
src/views/BeneficiaryDetail/StateButtons.tsx
src/views/BeneficiaryDetail/index.tsx

- Get User info from API instead of TheGraph;

Implement API request to get Beneficiary details

---

src/modals/WrongNetwork.tsx
yarn.lock

- Implement final layout for Wrong Network modal

Correct design for Wrong Network modal

---

src/components/Table.tsx
src/pages/manager/beneficiaries/[id].tsx
src/pages/manager/managers.tsx
src/utils/users.ts
src/views/Beneficiaries/BeneficiariesList.tsx
src/views/BeneficiaryDetail/StateButtons.tsx
src/views/BeneficiaryDetail/index.tsx
src/views/Manager/index.tsx
src/views/Managers/ManagersList.tsx
src/views/Managers/NoManagers.tsx
src/views/Managers/index.tsx
src/views/Profile/ContactForm.tsx

- Added some missing translations from Prismic;
- Fixed CircledIcon size in Beneficiaries and Managers list;

Add translations and views from Prismic

---

src/components/Table.tsx
src/modals/AddBeneficiary.tsx
src/views/Beneficiaries/BeneficiariesList.tsx
src/views/Beneficiaries/index.tsx

- Missing list refresh after adding a new beneficiary;

Refresh Beneficiaries list after adding a new one

---

src/views/Manager/Cards.tsx
src/views/Manager/ProgressBar.tsx
src/views/Manager/index.tsx
yarn.lock

- Fixed a small bug in the layout which caused items to not be aligned;

Layout fix in Manager dashboard

---

src/views/Proposals/AddCommunityPage.tsx
src/views/Proposals/ProposalsPage.tsx
src/views/Proposals/index.tsx

-When clicking a page, add to the url
Replace url for Requests tab » ?tab=requests

Proposals page dogfooding fixes

---

src/helpers/regex.ts
src/views/AddCommunity/CommunityForm.tsx
src/views/AddCommunity/ContractForm.tsx
src/views/AddCommunity/PersonalForm.tsx
src/views/AddCommunity/index.tsx
src/views/Profile/ContactForm.tsx

- New section for "Personal Info": User Photo, Name and Email (only shows this section if this info doesn't exist already);
- Commented "Private Community" and "Expected UBI duration" alert by Bernardo request;
- "Claim Amount" and "Max Claim" now are always in USD (and the input suffix shows the value in the User currency);

Improvements in Add Community page

---

src/modals/Stories/OpenStory.tsx
src/views/Stories/StoryList.tsx

Contribute button

---

package.json
src/pages/messages.tsx
src/utils/routes.ts
src/views/Messages.tsx
src/views/Notifications.tsx
yarn.lock

Messages page

---

src/api/community.ts
src/components/DonateCard.tsx
src/components/Map.tsx
src/components/Organization.tsx
src/components/Sidebar.tsx
src/components/SocialLink.tsx
src/modals/Contribute.tsx
src/modals/Stories/OpenStory.tsx
src/views/Community/Beneficiaries.tsx
src/views/Community/CommunityDetails.tsx
src/views/Community/index.tsx
src/views/Stories/StoryList.tsx

- Add promoter of a community
- Add generate proposal flow for pending communities
- Some fixes of bugs detected

Add community promoter, generate proposal and fixes

---

package.json
src/views/Community/CommunityDetails.tsx
src/views/Proposals/Community.tsx
yarn.lock

-New parameter "maxbeneficiaries" on generate proposal

proposals update

---

src/api/community.ts
src/helpers/toCamelCase.ts
src/modals/AddCommunity/CommunityEdited.tsx
src/modals/AddCommunity/ReloadInfo.tsx
src/modals/index.ts
src/pages/manager/communities/[id].tsx
src/utils/communities.ts
src/utils/routes.ts
src/views/AddCommunity/CommunityForm.tsx
src/views/AddCommunity/ContractForm.tsx
src/views/AddCommunity/PersonalForm.tsx
src/views/AddCommunity/index.tsx
src/views/EditCommunity/EditPending.tsx
src/views/EditCommunity/EditValid.tsx
src/views/EditCommunity/index.tsx

- Add Edit Community page (for pending and valid communities);
- Add missing translations from Prismic;

Add Edit Community page

---

src/api/community.ts
src/components/Filters.tsx
src/views/Beneficiaries/index.tsx
src/views/Communities/Content.tsx
src/views/Communities/Filters.tsx
src/views/Communities/index.tsx
src/views/Managers/index.tsx
src/views/Requests/index.tsx

 Communities: Search by name + Search by country + Map

---

src/helpers/generateCommunityProposal.ts
src/modals/Contribute.tsx
src/views/Beneficiaries/index.tsx
src/views/BeneficiaryDetail/index.tsx
src/views/Community/Beneficiaries.tsx
src/views/Community/CommunityDetails.tsx
src/views/Managers/index.tsx
src/views/Proposals/Community.tsx

[#199](https://github.com/impactMarket/app/issues/199)

Dogfooding high priority fixes

---

src/components/Image.tsx
src/views/Communities/Community.tsx
src/views/Community/CommunityDetails.tsx
src/views/Requests/Communities.tsx

Fix: Smaller Images in Community, Communities and Requests

---

src/modals/AddBeneficiary.tsx

Validate Beneficiaries

---

src/api/community.ts
src/components/Sidebar.tsx
src/components/UserMenu.tsx
src/views/Communities/Community.tsx
src/views/Communities/index.tsx
src/views/Community/Header.tsx
src/views/Community/ReviewState.tsx
src/views/Community/UserCard.tsx
src/views/Community/index.tsx
src/views/Proposals/AddCommunityPage.tsx
src/views/Proposals/Community.tsx
src/views/Requests/index.tsx

[DF]❗High Priority Fixes

---

src/views/Community/CommunityDetails.tsx

Translate Community Descriptions

---

src/components/Sidebar.tsx
src/components/UserMenu.tsx
src/views/Community/Header.tsx
src/views/Community/ReviewState.tsx
src/views/Community/index.tsx
src/views/Notifications.tsx

[DF] Low Priority Fixes

---

src/views/Community/Beneficiaries.tsx
src/views/Community/index.tsx

- Remove min and max tranche from the comunityEntity query

Bugfix on add managers in prod

---

src/helpers/generateCommunityProposal.ts
src/views/AddCommunity/index.tsx
src/views/EditCommunity/EditPending.tsx
src/views/Proposals/Community.tsx

[#212](https://github.com/impactMarket/app/issues/212)

Update community contract values

---

src/utils/communities.ts
src/views/AddCommunity/PersonalForm.tsx

This PR fixes #200 (partially)
This PR should be manually tested by @hugomarquesdev, included on reviewers.

Fix community form fields

---

customtypes/pwa-view-community/index.json
package.json
src/components/Sidebar.tsx
src/components/SocialLink.tsx
src/modals/AddBeneficiary.tsx
src/modals/AddManager.tsx
src/modals/Contribute.tsx
src/views/AddCommunity/PersonalForm.tsx
src/views/Beneficiary.tsx
src/views/Communities/Community.tsx
src/views/Communities/Header.tsx
src/views/Community/Beneficiaries.tsx
src/views/Community/CommunityDetails.tsx
src/views/Community/UserCard.tsx
src/views/Notifications.tsx
yarn.lock

This PR fixes #241 
This PR should be manually tested by @PauloSousapt, included on reviewers.

Dogfooding Fixes

---

package.json
yarn.lock

This PR bumps ui dependency to `1.5.0`

Bump UI to 1.5.0

---

src/components/Slider/Slider.tsx
src/components/Slider/SliderButtons.tsx
src/modals/Stories/OpenStory.tsx
src/views/Stories/StoryList.tsx

This PR fixes #213 
This PR should be manually tested by @psoaresbj , included on reviewers.

Update Stories UI

---

src/components/Table.tsx
src/hooks/useWallet.tsx
src/modals/Contribute.tsx
src/views/Beneficiaries/index.tsx
src/views/Community/Dashboard.tsx
src/views/Managers/index.tsx
src/views/Proposals/Proposal.tsx

This PR fixes:
- Can’t open any community 404 (in Requests) 
- Contribute Modal Messages
- Proposals Address Mobile Wrapping
- Delete cookies when disconnecting
- Manager / Beneficiaries search by name
This PR should be manually tested by @PauloSousapt , included on reviewers.

Dogfooding Fixes 17.08

---

src/views/Community/ManagersTab.tsx
src/views/Community/RolesTabs.tsx
src/views/Community/UserCard.tsx
src/views/Community/index.tsx
src/views/Requests/Communities.tsx
src/views/Requests/index.tsx

This PR fixes #245 
This PR should be manually tested by @psoaresbj , included on reviewers.

Requests: Filter by name and address + Manager's data

---

src/api/community.ts
src/components/CommunityCard.tsx
src/hooks/useCommunitiesCountries.ts
src/hooks/useCommunitiesReviewsByCountry.ts
src/views/Communities/CommunitiesList.tsx
src/views/Requests/Communities.tsx
src/views/Requests/Filters.tsx
src/views/Requests/ReviewTabs.tsx
src/views/Requests/index.tsx

This PR fixes #244 
This PR should be manually tested by @psoaresbj , included on reviewers.

Requests Tabs

---

src/hooks/useGuard.tsx
src/libs/Prismic/hooks/useTranslations.tsx
src/libs/Prismic/linkResolver.ts
src/pages/_app.tsx
src/pages/ambassador/index.tsx
src/pages/ambassador/reports.tsx
src/pages/api/exit-preview.ts
src/pages/api/preview.ts
src/pages/beneficiary.tsx
src/pages/communities/[id].tsx
src/pages/communities/index.tsx
src/pages/index.tsx
src/pages/manager/beneficiaries.tsx
src/pages/manager/beneficiaries/[id].tsx
src/pages/manager/communities/[id].tsx
src/pages/manager/communities/add.tsx
src/pages/manager/index.tsx
src/pages/manager/managers.tsx
src/pages/messages.tsx
src/pages/mycommunity.tsx
src/pages/notifications.tsx
src/pages/profile.tsx
src/pages/proposals.tsx
src/pages/requests.tsx
src/pages/settings.tsx
src/pages/stories.tsx

This PR adds support for 
This PR should be manually tested by @PauloSousapt included on reviewers.

Add support for preview

---

customtypes/pwa-modals/index.json
src/modals/Contribute.tsx

This PR fixes #221 
This PR should be manually tested by @obernardovieira @PauloSousapt @psoaresbj , included on reviewers.

Contribute Modal - Check your wallet info

---

src/components/Sidebar.tsx
src/hooks/useCommunities.ts
src/hooks/useCommunity.ts
src/views/MyCommunity.tsx

This PR should be manually tested by @obernardovieira @PauloSousapt @psoaresbj , included on reviewers.

My Community Page:  Button on Sidebar + Show Pending Community to Donor + useSWR for this page

---

.prismic-tasks-inputs/translations.json
customtypes/pwa-translations/index.json
package.json
src/components/DonateCard.tsx
src/components/UserCard.tsx
src/modals/AddCommunity/ReloadInfo.tsx
src/modals/Contribute.tsx
src/modals/Stories/CreateStory.tsx
src/views/AddCommunity/CommunityForm.tsx
src/views/Beneficiary.tsx
src/views/Community/CommunityDetails.tsx
src/views/Community/Header.tsx
src/views/Community/RolesGrid.tsx
src/views/Community/RolesTabs.tsx
src/views/Profile/index.tsx
src/views/Stories/StoryList.tsx
yarn.lock

This PR fixes #282 #283 
**Some fixes are in this UI's PR:**
https://github.com/impactMarket/ui/pull/150
This PR should be manually tested by @psoaresbj @PauloSousapt @obernardovieira , included on reviewers.

Dogfooding Fixes 12/09

---

.prismic-tasks-inputs/translations.json
customtypes/pwa-translations/index.json
customtypes/pwa-view-community/index.json
src/views/Beneficiary.tsx

This PR fixes #230 
This PR should be manually tested by @psoaresbj @obernardovieira @PauloSousapt , included on reviewers.

UBI / Beneficiary: Show days in countdown if hours > 24

---

.prismic-tasks-inputs/translations.json
customtypes/pwa-translations/index.json
customtypes/pwa-view-community/index.json
package.json
src/components/InfoCard.tsx
src/views/Community/InfoCards.tsx
src/views/Community/index.tsx
yarn.lock

This PR fixes #226 
This PR should be manually tested by @obernardovieira @psoaresbj @PauloSousapt , included on reviewers.

Community: Max per Beneficiary Tooltip

---

src/components/InfoCard.tsx

- Changed tooltip icon
This PR should be manually tested by @obernardovieira @psoaresbj , included on reviewers.

Fix: Tooltip Icon

---

src/views/Community/RolesGrid.tsx
src/views/Community/RolesTabs.tsx

- Hide merchants tab when there are no merchants.
This PR should be manually tested by @obernardovieira @psoaresbj , included on reviewers.

Fix: Merchants Tab

---

customtypes/pwa-modals/index.json
customtypes/pwa-view-community/index.json

This PR adds missing prismic data.
- 
This PR should be manually tested by @hugomarquesdev @obernardovieira @psoaresbj , included on reviewers.

Prismic data for edit community, cashin button and contribute messages

---

src/views/Community/index.tsx

This PR fixes #289 
- Hide dashboard on pending community
This PR should be manually tested by @psoaresbj @obernardovieira @PauloSousapt , included on reviewers.

Hide dashboard on pending community

---

src/api/user.ts
src/components/CommunityCard.tsx
src/components/Map.tsx
src/components/ShimmerEffect.tsx
src/components/Table.tsx
src/graph/community.ts
src/hooks/useBeneficiaries.ts
src/hooks/useBeneficiariesCount.ts
src/hooks/useCommunities.ts
src/hooks/useSuspiciousReports.ts
src/pages/communities/edit/[id].tsx
src/utils/routes.ts
src/views/Ambassador/Reports.tsx
src/views/Ambassador/index.tsx
src/views/Beneficiaries/BeneficiariesList.tsx
src/views/Beneficiaries/index.tsx
src/views/Communities/ClaimsMap.tsx
src/views/Communities/CommunitiesList.tsx
src/views/EditCommunity/CommunityManagementForm.tsx

- Add swr getter for the beneficiaries, 
- Add shimmer effect component, 
- Add graphql queries for comunity beneficiaries,
- Templating
- Add loading effects to community cards and claims map
This PR fixes #231 #217 
This PR should be manually tested by @obernardovieira @psoaresbj @hugomarquesdev , included on reviewers.

Ambassador dashboard updates

---

package.json
types/styled-gen/index.d.ts

- 
This PR should be manually tested by @psoaresbj , included on reviewers.

Styled-gen Types

---

config.ts
package.json
src/components/DonateCard.tsx
yarn.lock

- 
This PR should be manually tested by @psoaresbj @obernardovieira @hugomarquesdev , included on reviewers.

Cashin donations

---

customtypes/pwa-modals/index.json
src/api/user.ts
src/components/Sidebar.tsx
src/hooks/useWallet.tsx
src/modals/RecoverAccount.tsx
src/modals/index.ts
src/views/Communities/Header.tsx
src/views/Communities/index.tsx

This PR fixes #278 
- Option to recover account after beign deleted. This option shows in login.
This PR should be manually tested by @psoaresbj @PauloSousapt @obernardovieira , included on reviewers.

Recover Account

---

src/views/Beneficiary.tsx

- 
This PR should be manually tested by @obernardovieira, included on reviewers.

Capture exceptions errors at claim

---

src/modals/AddManager.tsx
src/views/Beneficiary.tsx
src/views/Community/RolesGrid.tsx
src/views/Community/RolesTabs.tsx
src/views/Community/index.tsx

- Refactor on the remove and add managers
- Capturing claiming exception errors
This PR fixes #313
- 
This PR should be manually tested by @obernardovieira @hugomarquesdev @psoaresbj , included on reviewers.

Bugfix ambassadors can't remove managers

---

src/utils/position.ts
src/views/Beneficiary.tsx

This PR fixes #316 
- If user had browser location disabled, claiming UBI threw an error (even tho the transaction worked)

Fix: Beneficiary Claim

---

src/views/AddCommunity/CommunityForm.tsx

This PR fixes #314 
- Community description limit to 1024 chars

Fix: Community Description

---

src/views/Manager/Alerts.tsx

Fix: Request Funds

---

src/views/EditCommunity/ContractDetailsForm.tsx

This PR fixes a bug changing the community base interval
- 
This PR should be manually tested by @obernardovieira @hugomarquesdev, included on reviewers.

Fix edit community base interval

---

.eslintrc.js
.eslintrc.yaml
.prettierrc.js
package.json
src/components/DonateCard.tsx
src/libs/Prismic/components/RichText.tsx
src/views/AddCommunity/ContractForm.tsx
src/views/Beneficiary.tsx
src/views/EditCommunity/ContractDetailsForm.tsx
yarn.lock

Fix edit contract details.
Also applied our eslint and prettier formats (prettier only to changed files)
Tried to add types, but requires refactoring.

fix edit community contract details

---

src/components/WrapperProvider.tsx

This PR fixes #330
Updates Libera logo and wallets list.

update libera wallet logo and wallets list

---

config.ts
package.json
src/components/WrapperProvider.tsx
src/helpers/generateCommunityProposal.ts
yarn.lock

This PR fixes the issues of connecting from the laptop. A QR is needed, but it was not showing up.
This was both tested on mobile and desktop with both Libera and Valora.
This PR should be manually tested by @PauloSousapt, included on reviewers.

bump utils and peer dependencies

---

src/components/CommunityDashboard/DashboardChart.tsx
src/views/Community/Dashboard.tsx

Fix: Charts Values

---

package.json
src/helpers/generateCommunityProposal.ts
yarn.lock

fix community creation proposal

---

package.json
src/components/WrapperProvider.tsx
src/hooks/useWallet.tsx
src/views/Proposals/ProposalsPage.tsx
yarn.lock

- Fixes deeplink with Android and especially iOS. To make it work with iOS, another update on the Libera wallet is coming up.

fix libera walletconnect

---

src/views/Communities/CommunitiesList.tsx
src/views/Communities/index.tsx
src/views/MyCommunity.tsx

This PR fixes reported bugs on the pwa
- 
This PR should be manually tested by @obernardovieira @hugomarquesdev , included on reviewers.

Fix communities pagination, fix mycommunity not redirecting

---

.prismic-tasks-inputs/translations.json
src/components/Stories/StoryInfo.tsx
src/views/Stories/StoryList.tsx

Stories: Change Contribute to Donate

---

next.config.js

This PR fixes #354
- Not sure if this could be the reason to some of the reported issues around cache, but since we are not making use of it, lets turn it off.

turn off pwa feature

---

src/components/Stories/StoryInfo.tsx
src/views/Stories/StoryList.tsx

Fix donate button font-size

---

src/components/DonateCard.tsx

Temporarily hide ramp feature to donate

---

package.json
src/hooks/learn-and-earn/useLevels.ts
src/pages/_app.tsx
src/pages/learn-and-earn/[level]/[lesson].tsx
src/views/LearnAndEarn/Helpers.tsx
src/views/LearnAndEarn/Level/Lesson.tsx
src/views/LearnAndEarn/Level/index.tsx
src/views/LearnAndEarn/LevelsTable.tsx
src/views/LearnAndEarn/Metrics.tsx
yarn.lock

- Translations
- Bump UI
- UI Adjustments

LAE updates

---

src/components/DonateCard.tsx
src/modals/Contribute.tsx

Fix Contribute to Donate

---

package.json
src/components/Tooltip.tsx
src/libs/Prismic/components/RichText.tsx
src/pages/_app.tsx
src/views/Communities/CommunitiesList.tsx
src/views/LearnAndEarn/Level/Lesson.tsx
src/views/LearnAndEarn/Level/index.tsx
src/views/LearnAndEarn/LevelsTable.tsx
src/views/LearnAndEarn/Metrics.tsx
src/views/LearnAndEarn/index.tsx
yarn.lock

- Add logic adjustments
- Bugfixes 
- Tooltip component

LaE bugfixes and updates

---

.github/workflows/publish-sentry.yml
tsconfig.json

Changes the config and fixes sourcemap uploads

change sentry publish

---

src/components/Trim.tsx
src/views/Home/Alerts/index.tsx
src/views/Home/index.tsx
src/views/Stories/StoryList.tsx

- Padding in shortcuts cards
- Stories: Trim in Community Name + Community City / Country

Fixes 06.02

---

src/components/Sidebar.tsx
src/hooks/useGuard.tsx

Fix check of the addresses to lowercase

---

src/hooks/useWallet.tsx

- Force local storage clean at disconnect
- 

Force local storage clean at disconnect

---

.github/workflows/publish-sentry.yml
next.config.js
package.json
yarn.lock

log tx data change deploy

---

next.config.js

add ignoreEmpty to sentry webpack

---

src/hooks/useCache.tsx
src/hooks/useGuard.tsx
src/hooks/useWallet.tsx
src/views/Home/index.tsx

This PR fixes cache issues
- Force session clean for staled users
This PR should be manually tested by @obernardovieira @hugomarquesdev , included on reviewers.

Force session clean for staled users

---

src/components/Table.tsx
src/components/WrapperProvider.tsx
src/helpers/handleKnownErrors.ts
src/helpers/handleSignature.ts
src/hooks/useGuard.tsx
src/hooks/useWallet.tsx
src/modals/AddBeneficiary.tsx
src/modals/AddManager.tsx
src/modals/Contribute.tsx
src/views/Beneficiary.tsx
src/views/BeneficiaryDetail/StateButtons.tsx
src/views/Community/CommunityDetails.tsx
src/views/Community/RolesGrid.tsx
src/views/EditCommunity/CommunityManagementForm.tsx
src/views/EditCommunity/ContractDetailsForm.tsx
src/views/Home/Alerts/Manager.tsx

This PR fixes Bugs
- Add info toasters to check the wallet on transaction
- Fix error on update community details
- Handle transaction known errors
- Bugfixes
This PR should be manually tested by @obernardovieira @hugomarquesdev , included on reviewers.

Add info toasters, handle error, bugfixes

---

.gitignore
sentry.client.config.ts

- Ignore specific errors to be sent to sentry

ignore false positive sentry errors

---

src/views/Home/index.tsx

Fix shortcuts not showing correct cads

---

src/views/LearnAndEarn/Metrics.tsx

Process LaE claim rewards transaction error

---

src/views/Community/Header.tsx
src/views/Community/ReviewState.tsx
src/views/Community/RolesTabs.tsx
src/views/Community/index.tsx
src/views/EditCommunity/EditCommunity.tsx
src/views/EditCommunity/EditPending.tsx
src/views/EditCommunity/index.tsx

This PR fixes #402 #413 
- Fix: not showing edit button for ambassadors
- Use ambassador endpoint

Ambassador Edit Button Fix

---

customtypes/pwa-modals/index.json
src/modals/AddBeneficiary.tsx
src/views/Beneficiaries/index.tsx

This PR fixes #345 
- Shows a message when the limit of beneficiaries is reached and doesn't allow to add more.

Max Beneficiaries Warning

---

customtypes/pwa-modals/index.json
customtypes/pwa-translations/index.json
customtypes/pwa-view-ambassador/index.json
package.json
src/api/community.ts
src/modals/AddBeneficiary.tsx
src/modals/AddManager.tsx
src/modals/Contribute.tsx
src/modals/RemoveCommunity.tsx
src/modals/ReportSuspiciousActivity.tsx
src/modals/index.ts
src/views/Beneficiary.tsx
src/views/BeneficiaryDetail/StateButtons.tsx
src/views/Community/Actions.tsx
src/views/Community/CommunityDetails.tsx
src/views/Community/Header.tsx
src/views/Community/ManagersGrid.tsx
src/views/Community/index.tsx
src/views/EditCommunity/CommunityManagementForm.tsx
src/views/EditCommunity/ContractDetailsForm.tsx
src/views/Home/Alerts/Manager.tsx
yarn.lock

This PR fixes #337 
- _Remove Community_ button for Council Members.

Remove Community button for Council Members

---

src/components/Tooltip.tsx
src/views/LearnAndEarn/Helpers.tsx
src/views/LearnAndEarn/Level/index.tsx
src/views/LearnAndEarn/LevelsTable.tsx
src/views/LearnAndEarn/index.tsx

This PR fixes
- Available tab not showing results for not connected users
- Add tooltip for users ineligible for L&E
This PR should be manually tested by @hugomarquesdev @obernardovieira , included on reviewers.

[LearnAndEarn] tooltip not eligible

---

customtypes/pwa-modals/index.json
customtypes/pwa-translations/index.json
customtypes/pwa-view-ambassador/index.json
src/graph/community.ts
src/helpers/dateHelpers.ts
src/views/Ambassador/Activity.tsx
src/views/Ambassador/index.tsx

Ambassador: Communities Last Activity Table

---

config.ts
next.config.js
src/views/Support/index.tsx

This PR fixes https://github.com/impactMarket/support-issues/issues/4
- 

fix support redirect

---

src/hooks/learn-and-earn/useLessons.ts
src/views/LearnAndEarn/Level/index.tsx

Show alert when there are no Rewards Available

---

customtypes/pwa-view-microcredit/index.json

Update prismic logic

---

src/components/Slider/Slider.tsx

Stories Slideshow Fix

---

src/views/MicroCredit/ClaimLoan.tsx
src/views/MicroCredit/LoanRepayment.tsx

Add error handling on microcredit

---

package.json
src/views/Beneficiary.tsx
src/views/Home/Alerts/Beneficiary.tsx
yarn.lock

Beneficiary: Components Overlap

---

src/components/Sidebar.tsx
src/hooks/useWallet.tsx

Sidebar: Language Dropdown for Logged Out Users

---

src/components/Sidebar.tsx
src/components/Table.tsx
src/views/LearnAndEarn/Level/index.tsx
src/views/MicroCredit/LoanRepayment.tsx

- Fix beneficiaries pagination, 
- Add sidebar layout and functional adjustments, 
- Fix L&E tooltip, 
- Update loan repayment text

Dogfooding and reported bugfixes

---

src/api/user.ts
src/components/Sidebar.tsx
src/helpers/dateHelpers.ts
src/hooks/useGuard.tsx
src/hooks/useMicrocreditBorrowers.ts
src/pages/microcredit-manager.tsx
src/utils/routes.ts
src/utils/users.ts
src/views/MicrocreditManager/BorrowersList.tsx
src/views/MicrocreditManager/MicrocreditManager.tsx
src/views/MicrocreditManager/Table.tsx

This PR fixes #445 
- https://app-git-feature-microcredit-repayments-ipct.vercel.app/microcredit-manager

Microcredit Manager: Repayments

---

package.json
src/views/MicroCredit/LoanRepayment.tsx
src/views/MicroCredit/index.tsx
yarn.lock

This PR fixes the loan full repayment, which includes this change https://github.com/impactMarket/utils/pull/226

fix loan full repay

---

package.json
yarn.lock

Remove: Slicemachine

---

src/hooks/learn-and-earn/useLessons.ts
src/views/MicroCredit/ClaimLoan.tsx
src/views/MicroCredit/LoanOverview.tsx
src/views/MicroCredit/LoanRepayment.tsx
src/views/MicroCredit/index.tsx

Add translations and dogfooding fixes

---

src/views/MicrocreditManager/BorrowersList.tsx
src/views/MicrocreditManager/MicrocreditManager.tsx
src/views/MicrocreditManager/Table.tsx

- Thinner table rows
- Translations
- New column: Last Repayment
- Small fixes

Fixes: Microcredit Repayment

---

package.json
yarn.lock

This PR fixes a loading details issue. It only bumps utils, since the fix is in utils itself. See https://github.com/impactMarket/utils/pull/224/commits/feed6c57d0ed2163c7c21b26039adfcf9ee9112b 

fix loading loan details (unstable) - bump utils

---

src/api/microcredit.ts
src/views/MicroCredit/Contract/ContractForm.tsx

Fix: Sign Contract

---

src/views/MicrocreditManager/BorrowersTab/BorrowersList.tsx

Manager Dashboard: Fix Claimed

---

src/components/Image.tsx
src/components/Stories/CommunityInfo.tsx
src/views/Stories/StoryList.tsx

Fix: Smaller Images

---

src/views/MicroCredit/LoanInReview.tsx
src/views/MicroCredit/index.tsx

Microcredit: In-review page

---

src/views/MicroCredit/RepaymentHistory.tsx
src/views/MicroCredit/index.tsx
src/views/User/Microcredit/RepaymentHistory.tsx

Repayment History Fix

---

src/views/MicrocreditManager/ApproveRejectTab/BorrowersList.tsx
src/views/MicrocreditManager/ApproveRejectTab/index.tsx

Fixes Dogfooding Microcredit Manager: 17 Aug

---

src/helpers/handleSignature.ts

This PR fixes questing signature on every page load and adds a captureException on signatures request.
- 

[bugfix] fix requesting loop signatures and captureException

---

src/modals/Microcredit/ApproveLoan.tsx

This PR updates loans interest to 0.2
- 

update loans daily interest to 0.2

---

src/components/Stories/Comments.tsx
src/components/UserMenu.tsx
src/hooks/useWallet.tsx
src/modals/AddCommunity/ConfirmAdd.tsx
src/modals/Contribute.tsx
src/modals/RecoverAccount.tsx
src/modals/RemoveCommunity.tsx
src/modals/ReportSuspiciousActivity.tsx
src/modals/Stories/CreateStory.tsx
src/modals/Stories/DeleteStory.tsx
src/modals/Stories/OpenStory.tsx
src/modals/Stories/ReportStory.tsx
src/views/AddCommunity/index.tsx
src/views/Community/CommunityDetails.tsx
src/views/Community/index.tsx
src/views/EditCommunity/CommunityDetailsForm.tsx
src/views/EditCommunity/ContractDetailsForm.tsx
src/views/EditCommunity/EditPending.tsx
src/views/Manager/Alerts.tsx
src/views/MicroCredit/Contract/ContractForm.tsx
src/views/Profile/index.tsx
src/views/Proposals/Community.tsx
src/views/Proposals/Proposal.tsx
src/views/Settings/index.tsx
src/views/User/StateButtons.tsx

Sentry: Capture Requests

---

src/components/WrapperProvider.tsx
src/pages/_app.tsx

This PR attempts to fix #516
- moved wagmiConfig to the root, as stated in https://github.com/wagmi-dev/references/issues/427
Not clear from tests.

[bugfix] fix stalled socket WalletConnect

---

.gitignore
next.config.js
package.json
sentry.client.config.ts
sentry.edge.config.ts
yarn.lock

This PR updates sentry dependency and attempts to improve sentry reports to show source code like it is in here https://impactmarket.sentry.io/issues/4404566328/?project=6171011&query=&referrer=issue-stream&statsPeriod=14d&stream_index=0,

update sentry dependency and improve reports

---

src/views/User/index.tsx

Fix: User Page: Microcredit Data

---

src/modals/Microcredit/ApproveLoan.tsx
src/views/MicroCredit/Application/FullWidthField.tsx
src/views/MicroCredit/Application/MobileBankerSelector.tsx
src/views/MicroCredit/Application/index.tsx
src/views/MicroCredit/RepaymentHistory.tsx
src/views/MicrocreditManager/ApproveRejectTab/BorrowersList.tsx
src/views/MicrocreditManager/ApproveRejectTab/index.tsx

- Fix Ui and logic bugs
This PR should be manually tested by @obernardovieira @hugomarquesdev, included on reviewers.

Microcredit fixes

---

src/views/Ambassador/Reports.tsx
src/views/Ambassador/index.tsx

Fix: Ambassador Suspicious Activity Page

---

sentry.client.config.ts

The goal of this PR is to improve the performance tracing, avoid what's happening on the screenshot below.
- 

[chore] improve sentry performance tracing

---

src/api/microcredit.ts
src/views/MicroCredit/Application/index.tsx
src/views/MicroCredit/index.tsx

In some cases we are seeing an infinite loading on borrowers page. This PRs attempts to fix that, reporting a crash to sentry on 100% of the cases.
Other changes
- Typed getBorrower and changed to lazy query

attempt fix loading borrower page

---

src/hooks/firebase/useFcmToken.tsx
src/hooks/useWallet.tsx
src/pages/_app.tsx

Fix: Firebase (Sentry Errors)

---

src/hooks/firebase/useFcmToken.tsx
src/hooks/useServiceWorker.tsx
src/hooks/useWallet.tsx
src/pages/_app.tsx

Fix: Firebase

---

src/components/FlexibleTab.tsx
src/components/Table.tsx
src/components/TooltipIcon.tsx
src/helpers/dateHelpers.ts
src/views/MicrocreditManager/ApproveRejectTab/BorrowersList.tsx
src/views/MicrocreditManager/RepaymentsTab/BorrowersList.tsx
src/views/MicrocreditManager/RepaymentsTab/index.tsx

- fix table horizontal scroll on mobile
- performance text on top of repayments table
- urgent tab
- tooltips with full dates
- fix filters ui breaking on mobile

Fixes: Loan manager Dashboard

---

src/components/Table.tsx
src/modals/Microcredit/ApproveLoan.tsx
src/views/MicrocreditManager/ApproveRejectTab/BorrowersList.tsx
src/views/MicrocreditManager/ApproveRejectTab/ChangeStatus.tsx
src/views/MicrocreditManager/ApproveRejectTab/StatusBadge.tsx
src/views/MicrocreditManager/MicrocreditManager.tsx
src/views/MicrocreditManager/RepaymentsTab/BorrowersList.tsx

- add reach maturity column on repayments
- fix dropdowns going under table
- fit table columns to content
- add urgent description
- approve loan modal: add limits to the maturity for multiple loan amounts
- refactor code (creating more components to keep everything organized instead of having 300+ lines of code per file)

Fixes: Loan manager Dashboard v2

---

next.config.js
package.json
yarn.lock

[bugfix] attempt to fix stale wss

---

tsconfig.json

Attempt to fix https://github.com/impactMarket/app/issues/567

bump tsconfig

---

src/views/User/Microcredit/ApplicationHistory/index.tsx

Fix: User Page: Microcredit status

---

src/helpers/handleSignature.tsx
src/modals/Signature.tsx

Fix: Signature error

---

src/views/Ambassador/index.tsx

Fix: Ambassador dashboard returns 404 for ambassadors without community

---

src/views/MicroCredit/Application/FormSection.tsx
src/views/MicroCredit/Application/FullWidthField.tsx
src/views/MicroCredit/Application/index.tsx

update docs upload microcredit application

---

package.json
src/modals/Microcredit/ApproveLoan.tsx
src/views/MicrocreditManager/ApproveRejectTab/ChangeStatus.tsx
yarn.lock

Show microcredit Approve button even when limit has been reached

---

package.json
yarn.lock

[bugfix] bump utils fixing borrowers page loading

---

src/views/MicroCredit/Contract/ContractForm.tsx

[bugfix] add missing application id contract signing

---

src/views/LearnAndEarn/Helpers.tsx
src/views/LearnAndEarn/LevelsTable.tsx
src/views/MicroCredit/Application/index.tsx
src/views/MicroCredit/Contract/ContractForm.tsx

This PR adds support to new tokens on Learn and Earn.
Related with https://github.com/impactMarket/backend/pull/971

[feature] [LearnAndEarn] add support other assets

---

src/components/Sidebar.tsx
src/hooks/useWallet.tsx
src/views/MicroCredit/Application/index.tsx
src/views/MicroCredit/Contract/ContractForm.tsx

Remove language redirect

---

src/views/Ambassador/index.tsx

Fix: Not showing all Communities on Ambassadors Dashboard

---

src/libs/Prismic/linkResolver.ts
src/pages/beneficiaries.tsx
src/utils/routes.ts
src/views/Ambassador/index.tsx
src/views/Beneficiaries/index.tsx
src/views/Manager/index.tsx

Fix: Beneficiaries List

---

src/views/MicrocreditManager/RepaymentsTab/BorrowersList.tsx

Fix: Borrowers Last Debt

---

.prettierignore
locales.config.js
sentry.client.config.ts

Add Luganda language to the locales

---

src/views/MicrocreditManager/RepaymentsTab/index.tsx

This PR fixes #619 
- 
This PR should be manually tested by @obernardovieira , @PauloSousapt , included on reviewers.

Feature: New defaulter filter on Microcredit Manager Dashboard

---

src/views/MicroCredit/LoanRepayment.tsx

Fix: Microcredit Debt Accrues

---

src/components/Filters.tsx
src/views/Beneficiaries/index.tsx
src/views/Communities/Filters.tsx
src/views/LearnAndEarn/index.tsx
src/views/Managers/index.tsx
src/views/MicrocreditManager/ApproveRejectTab/index.tsx
src/views/MicrocreditManager/MicrocreditManager.tsx
src/views/MicrocreditManager/RepaymentsTab/index.tsx
src/views/Requests/Filters.tsx
src/views/Requests/index.tsx

Feature: Microcredit Manager Search Bar

---

src/views/MicroCredit/Application/index.tsx

[fix] borrower not see application if approved

---

src/views/MicroCredit/Application/FullWidthField.tsx

Feature: Peruvian Currency in Microcredit Form

---

src/views/MicroCredit/Application/MobileBankerSelector.tsx

Feature: Microcredit manager countries from backend

---

package.json
yarn.lock

Fix: Loans Limit (Utils Update)

---

src/views/MicrocreditManager/RepaymentsTab/index.tsx

Fix: Microcredit Search Bar

---

package.json
yarn.lock

bump utils 4.2.0-beta.7 (fix ubi beneficiary edge case)

---

src/components/Sidebar.tsx
src/hooks/useWallet.tsx
src/modals/RecoverAccount.tsx
src/state/slices/auth.ts
src/views/Settings/index.tsx

This PR fixes #637 
- Small PR, big confusion and headache 😖

Feature: JWT Updates [PUT]

---

src/views/MicroCredit/LoanCompleted.tsx

Feature: New loan after finish repayment the last one

---

src/components/DonateCard.tsx

Fix: Raised > Goal

---

.prettierignore
src/views/MicroCredit/Application/MobileBankerSelector.tsx
src/views/MicroCredit/Application/index.tsx

Fix: Application Form UI

---

src/views/Ambassador/index.tsx

Fix: Ambassador Dashboard - Dropdown

---

src/views/Beneficiaries/BeneficiariesList.tsx
src/views/Managers/ManagersList.tsx
src/views/MicrocreditManager/MicrocreditManager.tsx

Fix: Managers and Beneficiaries endpoint: Search cant be empty

---

src/views/LearnAndEarn/Level/index.tsx
src/views/LearnAndEarn/Metrics.tsx

Add "Minimum of X tokens required to claim rewards" + Custom Error

---

config.ts

fix: config typo

---

src/api/user.ts
src/components/CheckPermission.tsx
src/components/ConnectWallet.tsx
src/components/Sidebar.tsx
src/constants/userTypes.ts
src/hooks/useGuard.tsx
src/utils/routes.ts
src/utils/users.ts
src/views/MicroCredit/index.tsx

…llet Component
- 
This PR should be manually tested by @Another-DevX , included on reviewers.

Feature: Added Borrower + Page permission component + Connect Wallet component

---

src/views/MicroCredit/LoanRepayment.tsx

fix: non-nullable values

---

src/views/MicroCredit/LoanRepayment.tsx
src/views/MicroCredit/index.tsx

chore: remove wrong maths and unused fixing

---

src/views/MicroCredit/LoanRepayment.tsx
src/views/MicroCredit/index.tsx

chore: remove wrong maths and unused fixing (#703)

---

src/views/LearnAndEarn/Metrics.tsx

L&E Need Help - Button

---

src/modals/Contribute.tsx
src/views/Beneficiary.tsx
src/views/Home/Alerts/Manager.tsx
src/views/MicroCredit/Contract/ContractForm.tsx
src/views/MicroCredit/LoanRepayment.tsx

Sentry Refactor

---

package.json
yarn.lock

feat: version 4.2.0

---

package.json
yarn.lock

feat: add impact market utils v4.2.1
